services:
  slidev:
    build: .
    ports:
      - "3030:3030"
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules # Questo "nasconde" la cartella locale per usare quella del container
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true